Sk 1.2update (#95)
* Initial push

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Notes and comment metadata added manually

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Adjusted formatting

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* @mkmurali Code updated and comments added

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Test controls

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Test controls

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Controls tested

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated impact to 0.5 based on Eugene's request

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* TypeError fix

* TypeError fix

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* URL change

* URL change

* Version update to 1.0.5

* Removing non-valid UTF-8 charactes: \x*

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated logic and tested section#1

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated logic and tested section#1

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated using the temporary logic of using CloudTrail input

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Tested

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Implemented checks for additional requirements and added comments for clarification

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated section 3 with aws_cloudtrail_trail input, removed describe.one and loop until describe.all can be used

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Tested and added the input statements where necessary after getting 'undefined local variable' errors

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Add conditions based on 1.2 requirements

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Added input keywords to address the 'undefined local variable or method' error

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Fixed unexpected end of output

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Fixed unexpected end of output

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Tested section#2

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Tested section#2

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated the benchmark version in README

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Fixed error in inspec.yml

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated inspec.yml

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Removed aws_cloudtrail_trail.rb library and prefixed control IDs with 'cis-aws-'foundations-'

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated logic with if-else for access keys

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated manual check to display usernames

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated manual check to display usernames

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Changed flow log to check status instead of traffic type

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Removed unused inputs

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated the README file to reflect the relevant inputs and versions

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Changed references of attributes to inputs

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Rony's new approach implemented for 3.x and 1.1

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Fixed spacing

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Gemlock file removed

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated 2.1 to remove input dependency

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Retrieved input value in 2.5

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Removed escape characters and added spaces where necessary in filter pattern strings

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Added code for an edge case

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Changed all occurences of 'attributes' to 'inputs'

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated the version in inspec.yml

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Updated the AWS resource pack URL and datatype names in inspec.yml

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Renamed as per the new naming convention

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* Added inspec_version requirement, removed gemfile and bundle install instructions

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

* update nist tag

* update nist tag

* Added the NIST tags

Signed-off-by: karikarshivani <karikarshivani@gmail.com>

Co-authored-by: ejaronne <34140975+ejaronne@users.noreply.github.com>